### ISSUE TITLE
temporary speed change

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warpd#46] opened 2022-03-19 08:16 UTC
Hello again!

When navigating, dynamic control of cursor speed would be useful, i.e. keys which increase or decrease the cursor_speed value while being pressed.

From an implementation point of view, it would probably be much simpler to just introduce "fast" and "slow" variants of the cursor movement commands, i.e. `cursor_speed`, 'cursor_speed_slow`, `cursor_speed_fast` and the same for left, right, up, down.

**Comment by kuapi0** [comment] 2022-03-19 17:34
I second this.

**Comment by rvaiya** [comment] 2022-03-19 20:42
I've been meaning to add configurable pointer acceleration to account for the gap between macoscopic and fine movement. I'm not opposed  to also adding some kind of explicit speed toggle, but I wonder if the former might be sufficient.

**Comment by herrsimon** [comment] 2022-03-19 22:35
To make this solution feature complete, there should also be kinetic movement (as present in trackpoint hardware as well as qmk and uhk), so that as soon as a movement key is pressed the pointer gets accelerated according to some quadratic curve. Short presses thus cause slow and precise movements while longer presses can cover distances. However, as this is probably a bit involved, I suggested incorporating full mouse control in keyd, see my other comment at https://github.com/rvaiya/keyd/issues/158

**Comment by rvaiya** [comment] 2022-03-20 00:15
> so that as soon as a movement key is pressed the pointer gets accelerated according to some quadratic curve

Indeed. This is what I meant by 'pointer acceleration'. There is already similar logic for scrolling (scroll velocity increases with time). The older version even had something called 'scroll flinging' which was fully inertial scrolling to which you could impart an impulse by tapping the scroll key for a second or third time, but I ended up removing it after realizing it wasn't very useful for most scrolling tasks, and probably counter productive in most cases.

**Comment by rvaiya** [comment] 2022-03-25 23:20
Pointer acceleration is now enabled by default in the latest release. I've picked default which feel reasonable on my machine, but you may want to play with the `acceleration` and `max_speed` variables. If you still feel the need for dedicated keys after using this for a bit let me know :).

**Comment by herrsimon** [comment] 2022-04-05 08:28
Thank you very much, have been using it for about a week now and it works like a charm! On my trackpoint-less keyboards I still miss a “quick move” possibility (for covering mid-range distances for which a hint-mode jump would take too long) but this is definitely not urgent, nor critical. If you decide and find the time to implement it: How about a generic action, which would disable acceleration and sets `speed` to a given argument while the corresponding activation key is held down? This way one could either slow down or speed up movement.
Another option would be to just multiply `speed`, `acceleration` and `max_speed` by some factor, but this seems less useful to me.

**Comment by rvaiya** [comment] 2022-04-12 03:41
I'm closing this for now. Feel free to reopen it if you feel the issue is unresolved.

**Closed by rvaiya** 2022-04-12 03:41 UTC
Labels: Feature Request, todo, implemented

**Comment by herrsimon** [comment] 2022-04-24 19:06
Again I'm very late with a reply, sorry for this. The acceleration feature works like a charm (as was to be expected) and I'm actually using it quite often. Thanks again, I really can't stress enough how useful warp/keyd are for me! They solved all the input problems I had been struggling with for years, and the longer I use them, the more I get the impression that all the feature requests I'm posting here are just desperate attempts to convince myself that there can't be software which is almost perfect (another such attempt is my inclusion of the word 'almost').
