### ISSUE TITLE
Shift/Ctrl + Clicks

### ISSUE THREAD

**Issue by ChrispyChris** [rvaiya/warpd#86] opened 2022-04-07 21:57 UTC
Was this feature ever considered? I first attempted to use a shift click and realized it conflicted with the middle screen key, but then attempted a control click and had no luck either. Is this something easily done or does it conflict with the mouse/keyboard aspect of this all?

**Comment by rvaiya** [comment] 2022-04-07 22:46
I've never seen the need for it. What is your use case? If you want to open links in a new tab in your browser you can already achieve this using middle click (`,`).

**Comment by ChrispyChris** [comment] 2022-04-08 20:25
It's actually more for when I'm doing things in the browser or when I'm using a program and doing selections on things such as files. If you have three files in order, clicking the first will highlight that, then holding shift+clicking the last will select all the files in between, in this example the second, as well as the file clicked. When using control+click, only each additional file clicked will be added to the selection group.

I use this for different things depending on what application I'm using. In my seedbox, I select multiple torrents and perform different actions on groups of them while using this method. Admittedly it's probably not the most useful thing to everyone out there, but shift and control clicking is something I actually did find myself doing frequently. Just figured I'd put it in an issue. 

Again, I've been really loving this application! The hinting and then making small adjustments like I saw you mention elsewhere has been amazingly quick! Thanks again!

**Comment by rvaiya** [comment] 2022-04-09 05:45
Thanks for the detailed use case. I've included support for this in the latest commit. Let me know if you encounter any bugs.

**Comment by ChrispyChris** [comment] 2022-04-10 00:08
No problem at all. I really love this program, so thank you for writing it. It's become one of my favorite pieces of software haha. Just as I was becoming more and more frustrated with Vimium, I saw this! 

Everything seems to be working fine as far as shift and control clicking now. If you feel comfortable closing this now, I am personally more than satisfied with the fix. 

Thanks again!

**Comment by rvaiya** [comment] 2022-04-10 08:08
Thanks :). I'm closing this for now

**Closed by rvaiya** 2022-04-10 08:08 UTC

**Comment by fboumol** [comment] 2022-06-10 16:24
Sorry to bother about this issue, but I cannot find how to make a ctrl+click.

What's the method (keystrokes?) to accomplish making a left click while ctrl (or any other modifier key) is pressed?

**Comment by ChrispyChris** [comment] 2022-06-12 01:17
I believe that once you've updated far enough, it should just work. After I mentioned it to the author, he fixed it pretty quick for me. 

Are you having issues with control and shift clicking? What's the problem @fboumol ?

**Comment by rvaiya** [comment] 2022-06-12 05:49
@fboumol What platform (X/wayland/macos) are you using?. This was implemented for macos and X.

**Comment by fboumol** [comment] 2022-06-12 21:14
I am working using X (under ubuntu 20.04 with xmonad). The problem is that, inside normal (cursor) mode launched with `warpd --normal` (not with the daemon) , I do not get any effect when pressing "m" (for my left click) together with "ctrl" modifier. The same problem applies to the shift modifier and to the other two buttons.

**Comment by rvaiya** [comment] 2022-06-13 05:57
Sorry, it looks like this was indeed broken. The latest commit should fix it.
