### ISSUE TITLE
regressions in normal mode?

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warpd#144] opened 2022-07-07 11:49 UTC
With the recently scriptability improvements, I noticed two things which appear to be unintended:

1. When combining `--oneshot` with `--normal`, starting a drag operation and then trying to jump using hints exits immediately and prints some garbage to stdout.

2. warpd now also exits (with the pressed button as exit code) when running as a daemon (or via `--foreground`) and one of the oneshot mouse buttons is pressed in normal mode.

**Comment by rvaiya** [comment] 2022-07-07 18:45
> When combining --oneshot with --normal, starting a drag operation and then trying to jump using hints exits immediately and prints some garbage to stdout

This is by design. The behaviour of the oneshot flag is to terminate warpd as soon as the mode of interest has completed.

> warpd now also exits (with the pressed button as exit code) when running as a daemon (or via --foreground) and one of the oneshot mouse buttons is pressed in normal mode.

Oops :P. This should be fixed.

**Comment by rvaiya** [comment] 2022-07-09 05:25
> I see, but then instead of exiting when trying to enter another mode, wouldn't it be better to ignore the keypress and exclusively exit when pressing an exit key, a print key or clicking the mouse?

The behaviour of `--oneshot` is simply to modify the behaviour of the initial mode so it terminates immediately after selection. In the case of normal mode this is inherently ambiguous. What you describe is probably more useful behaviour, but also a bit less consistent. 

Having said that, I've added it to the latest commit. I'm closing this for now. Feel free to reopen it if you feel it is unresolved.

**Comment by rvaiya** [comment] 2022-07-09 05:25
> I see, but then instead of exiting when trying to enter another mode, wouldn't it be better to ignore the keypress and exclusively exit when pressing an exit key, a print key or clicking the mouse?

The behaviour of `--oneshot` is simply to modify the behaviour of the initial mode so it terminates immediately after selection. In the case of normal mode this is inherently ambiguous. What you describe is probably more useful behaviour, but also a bit less consistent. 

Having said that, I've added it to the latest commit. I'm closing this for now. Feel free to reopen it if you feel it is unresolved.

**Closed** 2022-07-09 05:25 UTC
