### ISSUE TITLE
Mouse pointer disappears in normal mode.

### ISSUE THREAD

**Issue by MMAGANADEBIA** [rvaiya/warpd#66] opened 2022-03-31 00:51 UTC
Almost all the things works fine, except for one.
When I enter in normal mode, the mouse pointer disappears. I still can seen the interaction with some elements and use the `m`, `,` and `.` but I don't see where the pointer is.
Also the config file is not in my .config route, idk if I need to create it, download or is othe issue.

**Comment by rvaiya** [comment] 2022-03-31 01:02
Can you clarify what you mean by 'disappears'? If you are referring to the actual mouse pointer, then this is expected. If you are referring to the normal mode indicator (a small green square by default), then this should not be happening.

**Comment by MMAGANADEBIA** [comment] 2022-03-31 02:41
Both of them.
As I say, it works fine, but just I don't see the indicator, in this case the small green square.
I'm using a Debian based distro, if that helps.

**Comment by rvaiya** [comment] 2022-03-31 05:16
What distro/DE are you running? Do you have a compositor running? Does this happen in every application, or only some?

**Comment by MMAGANADEBIA** [comment] 2022-03-31 06:24
I'm using ParrotOS, bspwm and picom.
And this happend in every application.
I'm using a secondary monitor with my laptop.

**Comment by rvaiya** [comment] 2022-03-31 20:06
> I'm using a secondary monitor with my laptop.

Multiscreen setups are unsupported. Have you tried it without a second screen plugged in?

**Comment by rvaiya** [comment] 2022-03-31 23:32
> In fact, the M-A-x put the hints behind my windows.

This is a different issue from multi screen support. Can you try the latest commit? I believe it should be fixed.

Proper multi-screen support is still in the pipeline.

**Comment by MMAGANADEBIA** [comment] 2022-04-01 01:27
At least the hints are fixed, but the green square is still missing.

**Comment by rvaiya** [comment] 2022-04-07 07:59
Can you try the latest version? I believe your problems were related to your secondary monitor.

**Comment by MMAGANADEBIA** [comment] 2022-04-07 19:14
The problem has not disappear.
I tried in a single monitor too (laptop), and I have the same problem.
It could be a problem with picom?
I wanted to try it in MATE but I have a problem changing the DE.

**Comment by MMAGANADEBIA** [comment] 2022-04-08 17:50
I just tried in MATE and works fine, the square is orange and appears in every mode.
Seems to be a problem with picom or bspwm probably.

**Comment by rvaiya** [comment] 2022-04-08 18:19
I can't seem to reproduce this. Have you modified your picom config? Are
you running the latest version (`warpd -v`)?

**Comment by MMAGANADEBIA** [comment] 2022-04-08 22:04
Ok, I was trying to change mi picom configuration looking whats wrong and apparently the `backend = "glx"`  option cause the problem.
the `experimental-backends` can stay true, but the `glx` option is the cause of it.
So, I think that's the problem.
Hope more people see this thread and can identify the problem.
The only problem is that my rounded corners will look ugly. haha.
I will be thankful if you work in some solution from warpd side!!

**Comment by rvaiya** [comment] 2022-04-09 00:10
I still haven't been able to reproduce this, but I've made some changes which I suspect might help. Can you try the latest version?

**Comment by MMAGANADEBIA** [comment] 2022-04-09 00:30
The pointer is still mising and know if I let the backend with the glx option, mi OS become incredible slow, but I don't why, if it is caused because warpd or glx crash whit it.

**Comment by rvaiya** [comment] 2022-04-09 00:49
Can you post the minimal steps needed to reproduce this using a clean setup? Including a full `picom.conf` and the output of `warpd -v`.

**Comment by MMAGANADEBIA** [comment] 2022-04-09 22:59
1.- Copy and clone the master branch from the repository and then cd the folder.
2.- Inside the folder I do: `make && sudo make install`
In this last version, I have this message but no a error:
![screenshot-2022-04-09-05_47](https://user-images.githubusercontent.com/42789411/162594071-c493138a-a8c1-4d84-a985-e2fdca7a0983.jpg)
3.-  In my terminal: `warpd -f` to see if I have a problem.
![screenshot-2022-04-09-05_58](https://user-images.githubusercontent.com/42789411/162594312-806c5f42-a5a3-411e-a5d1-7de51cde9b87.jpg)

4.- Run warpd -v got:
![screenshot-2022-04-09-05_54](https://user-images.githubusercontent.com/42789411/162594226-ec1047d2-7ca0-4669-ae97-470ff9e972b3.jpg)

5.- In my picom config:
![screenshot-2022-04-09-05_55](https://user-images.githubusercontent.com/42789411/162594245-2a483dd9-3bb9-40e2-ac5f-e3c4c82a3c6f.jpg)
The last option, in the line 4, is the option that I said if I delete, all works fine and if stay, everything becomes slow.

**Comment by rvaiya** [comment] 2022-04-09 23:35
Please post your full `picom.conf` as text, and state your DE/OS. You should also go through these steps yourself on a fresh install to ensure they are minimum ones necessary to reproduce the issue.

**Comment by rvaiya** [comment] 2022-04-15 05:42
Closing due to inactivity and because I can't reproduce this. If someone else can provide steps to reliably do so, please open a new thread.

**Closed by rvaiya** 2022-04-15 05:42 UTC
Labels: heisenbug

**Comment by okwellok** [comment] 2022-06-05 10:36
Use archlinux+awesomewm+picom-git. I  just put the warpd class  in to picom.conf rounded-corners-exclude  rule, and work fine.
`rounded-corners-exclude = [
  "class_g = 'awesome'",
  "class_g = 'warpd'",
];
`
