### ISSUE TITLE
Drag mode issues

### ISSUE THREAD

**Issue by wearpants** [rvaiya/warpd#52] opened 2022-03-20 23:31 UTC
Entering Drag mode from grid mode doesn't seem to work correctly - I'm trying to using it to select text, and it seems to enter normal mode instead (ie, nothing is selected). If I hit the drag mode toggle in this state, it still doesn't work (ie nothing is selected).

Also a regression from pre-OS X: hitting button one wh
[config.txt](https://github.com/rvaiya/warpd/files/8312395/config.txt)
en in drag mode would previously exit the mode but now sends a click.

**Comment by rvaiya** [comment] 2022-03-21 00:16
> Entering Drag mode from grid mode doesn't seem to work correctly - I'm trying
> to using it to select text, and it seems to enter normal mode instead 

This is by design. It should drop you into normal mode *and* activate drag
mode. From normal mode you can use the movement keys to select text, or
reactivate one of the macroscropic modes using `g` or `x`.

> Also a regression from pre-OS X: hitting button one when in drag mode would
> previously exit the mode but now sends a click.

This was also an intentional design change. You can exit drag mode by pressing the
drag key again, or by using the exit/copy key.

**Comment by wearpants** [comment] 2022-03-21 00:26
> > Entering Drag mode from grid mode doesn't seem to work correctly - I'm trying
> > to using it to select text, and it seems to enter normal mode instead
> 
> This is by design. It should drop you into normal mode _and_ activate drag mode. From normal mode you can use the movement keys to select text, or reactivate one of the macroscropic modes using `g` or `x`.

That's the behavior I'm expecting, but it doesn't work correctly. From grid mode, I activate drag and move around but nothing is selected. In that state If I then activate drag *twice* it works correctly.

> This was also an intentional design change. You can exit drag mode by pressing the drag key again, or by using the exit/copy key.

Seems fine :-)

**Comment by rvaiya** [comment] 2022-03-21 00:34
> That's the behavior I'm expecting, but it doesn't work correctly. From grid mode, I activate drag and move around but nothing is selected. In that state If I then activate drag twice it works correctly.

Odd, I can't seem to reproduce this. To clarify, you are suggesting the following does not work:

 - Activate grid mode
 - Move the cursor over some text
 - Activate drag mode (press v)            <--- should drop you into normal mode with left mouse down
 - Move around to select some text
 - Terminate with `c`

**Comment by wearpants** [comment] 2022-03-21 00:49
OK this is super weird, it works correctly everywhere *except Safari*

**Comment by rvaiya** [comment] 2022-03-21 22:22
I can't seem to reproduce it in Safari either.

**Comment by rvaiya** [comment] 2022-04-07 07:56
I'm closing this for now. Feel free to re-open it if the issue is unresolved.

**Closed by rvaiya** 2022-04-07 07:56 UTC
