### ISSUE TITLE
MacOS M1，does not work

### ISSUE THREAD

**Issue by Fatpandac** [rvaiya/warpd#107] opened 2022-05-03 19:28 UTC
<img width="296" alt="image" src="https://user-images.githubusercontent.com/30423976/166550721-4ff4d553-7d4f-4389-a07d-a2c8f386f4ca.png">

**Comment by qyxtim** [comment] 2022-05-03 20:20
This problem may be caused by the new update. I solve it by switching to the previous commit `133b8a2`.

**Comment by rvaiya** [comment] 2022-05-03 22:43
Oops. This should be fixed in the latest commit.

**Comment by Fatpandac** [comment] 2022-05-04 03:27
> This problem may be caused by the new update. I solve it by switching to the previous commit `133b8a2`.

Think you.

**Comment by rvaiya** [comment] 2022-05-04 04:48
@Fatpandac To clarify, this shouldn't be necessary anymore.

**Closed by rvaiya** 2022-05-04 04:48 UTC

**Comment by Fatpandac** [comment] 2022-05-04 04:53
@rvaiya Yeah, it is solved on the latest commit, thx.
