### ISSUE TITLE
Capslock as Escape remapping not recognized by warpd (setxkbmap and xmodmap)

### ISSUE THREAD

**Issue by JarnoB** [rvaiya/warpd#61] opened 2022-03-30 15:10 UTC
I'm having some issues with the recognition of my setxkbmap mapping (`setxkbmap -option caps:escape`), which I use to map my caps lock as a second escape key. I did find this thread about a similar issue with xmodmap:

https://github.com/rvaiya/warpd/issues/23

I tried using xmodmap instead of setxkbmap using the script/remapping as mentioned by @rvaiya, but got some xmodmap related errors. So instead I used this xmodmap command to do the remapping: `xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'`

This mapping worked on most of the system, but just like my original setxkbmap, warpd doesn't recognize caps-lock as an escape-key.

With both bindings I made sure to (re)launch warpd after doing the remap. I also checked with xev to make sure that caps-lock is actually recognized as Escape, which it does.

I installed warpd via the AUR.

**Comment by rvaiya** [comment] 2022-03-30 17:54
warpd uses xinput to get around certain limitations in the X input system. Unfortunately this means that certain X remapping tools won't work properly. To avoid this, you can use an evdev based remapping tool like [keyd](https://github.com/rvaiya/keyd).  I've added a note about this in the man page.

**Comment by rvaiya** [comment] 2022-03-30 18:00
I'm closing this for now, but feel free to reopen it if you feel the issue is unresolved.

**Closed by rvaiya** 2022-03-30 18:00 UTC

**Comment by JarnoB** [comment] 2022-03-30 20:20
Thanks, I will check it out!
