### ISSUE TITLE
Fails on Wayland

### ISSUE THREAD

**Issue by dit7ya** [rvaiya/warpd#94] opened 2022-04-28 07:31 UTC
I just tried to compile it on Wayland on NixOS. Running `bin/warpd --hint` results into the following error

```
❯ ./bin/warpd --hint
listener function for opcode 4 of wl_output is NULL
fish: Job 1, './bin/warpd --hint' terminated by signal SIGABRT (Abort)
```

**Comment by rvaiya** [comment] 2022-04-28 09:04
What compositor are you using?

**Comment by Cadair** [comment] 2022-04-28 09:10
I am also getting this error on arch / sway. I pushed the PKGBUILD I am using here: https://aur.archlinux.org/packages/warpd-wayland-git

```
$ warpd --hint
listener function for opcode 4 of wl_output is NULL

Aborted (core dumped)
```

**Comment by rvaiya** [comment] 2022-04-28 09:13
Can you try the latest commit?

**Comment by Cadair** [comment] 2022-04-28 09:27
It no longer errors but nothing happens.

When the limitations says "no multi-monitor support" does that mean only works on the active display? because I am running a multi-monitor setup.

Thanks again!!

**Comment by roland-rollo** [comment] 2022-04-28 10:17
If I do `warpd --hint` it works (thanks again!) <3

It works for my if I only have one monitor. If I plug second it doesn't work. I use too arch/sway (and you AUR package Cadair).

**Comment by dit7ya** [comment] 2022-04-28 10:40
It does run with the latest commit. However, a red square gets drawn at the place of the mouse and that does not go away, neither can I see the effects of clicking the mouse buttons. The only way to get out of that, seems like, is to hit Alt n, which exits the running command.

**Comment by rvaiya** [comment] 2022-04-28 17:41
@dit7ya 

The red square represents the cursor. warpd normally hides the real cursor, but wayland doesn't seem to provide a mechanism  that allows clients to do this. You can get rid of the visual indicator by setting `cursor_size` to 1.
 
There are also several other warts, as mentioned in the README. I would recommend carefully reading the man page and/or trying it in X to have a better idea of what is broken on wayland.

@Cadair 

Multi monitor setups are completely unsupported, though it shouldn't be too hard to fix. I will have a go at it later today.

**Comment by rvaiya** [comment] 2022-04-29 22:03
This was actually a little more cumbersome than I thought. I've added full multi-screen support to the latest release, but will probably go on a short development hiatus barring any major issues.

**Comment by fedoranvar** [comment] 2022-05-03 14:17
tested on wayland with `6eee04` commit:

1) `sway` works fine
2) `wayfire` - shows the grid, pointer, and hints, but it didn't respond for control keys (`esc`, `hjkl`, `m,.`)

**Comment by Cadair** [comment] 2022-05-03 15:49
Appears to work well on my multi-monitor sway setup! Thanks so much @rvaiya :rocket:

**Comment by rvaiya** [comment] 2022-05-08 07:20
Thanks for the confirmation. I'm closing this issue for now.

@fedoranvar 

I will try and reproduce this when I have some time. Feel free to open a dedicated issue if you are affected by it.

**Closed by rvaiya** 2022-05-08 07:20 UTC
