### ISSUE TITLE
Feature Request:  Multi-monitor Support

### ISSUE THREAD

**Issue by tnotm** [rvaiya/warpd#62] opened 2022-03-30 17:48 UTC
This is by far one of the useful applications I have seen in sometime!  I appreciate your work on this.

This is a request for multi-monitor support.  I run warpd but nothing happens with a mulit-monitor setup.  This is noted in the README :)

**Comment by rvaiya** [comment] 2022-03-30 18:27
Thanks :). I was expecting this request at some point. Adding this is a bit of a pain,  but given the recent influx of interest I am inclined to invest some more time in it.

**Comment by gr4kk3r** [comment] 2022-03-30 22:00
I'll be waiting for the multi-monitor support. I wish I had the skills to help out, this is something I've wanted for years.

**Comment by Enzime** [comment] 2022-03-31 15:25
Just tested `v1.0.2-beta` and all three modes work fine with my dual monitors (which are the same resolution) :+1:

Would recommend anyone who wants to try this program to make sure you try entering a mode after launching it e.g. `Alt+Super+x`

**Comment by rvaiya** [comment] 2022-04-01 06:18
@Enzime This is probably because X treats all your displays as one giant screen by default. This is fine for hint and normal mode on X (ignoring scaling issues), but not ideal for grid mode and completely broken on OSX (which doesn't do this). My goal is add proper screen awareness so each screen can be manipulated in isolation and quickly warped to as an independent unit.

**Comment by GoodGuyPat** [comment] 2022-04-04 14:00
Hey! I have a setup such as below (Linux) and am happy to help out with some testing. Shame that I don't know C.

![image](https://user-images.githubusercontent.com/82534925/161560353-0e25d3fb-2260-4a08-83b0-404344ac476f.png)

**Comment by toastisme** [comment] 2022-04-05 10:39
Both hint and grid mode work fine for me with multiple monitors on Linux. All that's really needed is a higher grid density for hint mode.

**Comment by GoodGuyPat** [comment] 2022-04-05 10:50
As long as the monitors are alligned in one single axis, that is true. It gets a bit weird with different orientations:

![image](https://user-images.githubusercontent.com/82534925/161738099-e0d18426-b532-4c13-bb07-935f909a5585.png)

Would be cool if the software would display the grid only on the active display, but that may be out of scope.

**Comment by rvaiya** [comment] 2022-04-07 07:48
I've added experimental support for this in the latest commit. warpd should now treat each screen as an independent unit and will activate on the one currently containing the pointer. There isn't currently an easy way to switch screens without using your mouse, but I intend to remedy that shortly. Most of the hard work has been done, so it shouldn't be too difficult to make further adjustments. 

I expect macos and X to have a different set of ~~bugs~~ features, so all testing is greatly appreciated :P.

@GoodGuyPat Thanks for the offer. I only have a single screen to test on, so feedback would be helpful.

For those leaving feedback, please don't forget to state which version you are running (Linux/OSX).

**Comment by GoodGuyPat** [comment] 2022-04-07 08:19
Hey! I just tested it, it does exactly what you described and, regarding the cursor window, I would assume this to not be a big issue because chances are most of us nerds trying to go mouseless are already on a tiling window manager.

In my case I'm on i3, kernel 5.13.0-39-generic. Only issues I found with this version are:

1. In vertically oriented monitors the grid is borked (see below).
2. For some reason, if I open a VM with mouse and keyboard capture (vm workstation in this case) warpd will just crash the second that VM gets focus. Output of .config/warpd/warpd.log is a single line: `Starting warpd: 1.1.0-beta`.

Still, awesome work! Makes it perfectly usable for multimonitor. Full screen media is also not an issue, even on a separate screen.

Thanks for the update!

![image](https://user-images.githubusercontent.com/82534925/162153413-8053f97a-ca6b-430e-96b4-de69b0c2a3d2.png)

**Comment by rvaiya** [comment] 2022-04-08 07:04
Thanks for the update.

> In vertically oriented monitors the grid is borked (see below).

A temporary solution to this is to adjust `hint_size`. 

> For some reason, if I open a VM with mouse and keyboard capture (vm workstation in this case) warpd will just crash the second that VM gets focus. Output of .config/warpd/warpd.log is a single line: Starting warpd: 1.1.0-beta.

To clarify, are you suggesting this worked on earlier versions? One of warpd's limitations is that it won't work with applications that use xinput (and may indeed crash). VMs generally fall into this category, though I'm not sure about VM workstation in particular. If it is a regression, then I will investigate, but I am otherwise naturally inclined to assume the programs are fundamentally incompatible.

**Comment by GoodGuyPat** [comment] 2022-04-08 07:08
Hey.

> To clarify, are you suggesting this worked on earlier versions?

No, I have not tested in the previous one. I can checkout the earlier one if you're curious.

> A temporary solution for this is to adjust hint_size.

How'd I do that? Didn't see any mention to configurability in the readme.

**Comment by rvaiya** [comment] 2022-04-08 07:26
@GoodGuyPat In the man page there is salvation ;)

**Comment by GoodGuyPat** [comment] 2022-04-08 07:40
I was not aware of a manpage being included, it is great!
> Unfortunately I am not aware of a good solution to this problem.
I can only offer uneducated guesses. It is worth mentioning that there is no misbehavior by the system when (in this case) VMWare catpures the mouse and keyboard, other than warpd stopping. Additionally, I have just tested a VirtualBox VM (I know, I know...) and it has not reproduced the issue.

For now, if I am bound to use VMWare, I will just run warpd undaemonized inside a while True loop in a python script and pretend I am not ashamed of myself.

**Comment by dsych** [comment] 2022-04-08 14:22
Just tested it out and it works for the most part! Some bugs that I noticed:
1. When moving cursors in normal mode between screens, it only works when going from `additional -> main` display. The other way around (`main -> additional`) the cursor just bumps into the screen edge. 
2. When going between displays in normal mode, cursor "appears" at the transfer point on the source display, while actually moving on the destination display. I think this is just a visual bug as the cursor behaves correctly otherwise.
3. Moving the cursor `with a mouse` in normal mode transfers the cursor between screens correctly. Albeit, the cursor artifact from the second point remains.

I have 2 moniotrs

**Comment by rvaiya** [comment] 2022-04-08 18:31
> When moving cursors in normal mode with a keyboard between screens, it only works when going from additional -> main display. The other way around (main -> additional) the cursor just bumps into the screen edge.

This is actually unsupported. The fact that you can do it at all is a bug :P.

> 2/3

A consequence of 1 :P 

The user is expected to switch screens using the new screen selection mode `A-M-s`. Moving directly between them should soon be impossible.

**Comment by rvaiya** [comment] 2022-04-09 00:16
@GoodGuyPat The hint issue should be solved in the latest version.
@dsych The boundary issues should also be fixed.

I'm closing this thread for now since the feature has been implemented, but feel free to create individual issues if you encounter any bugs.

**Closed by rvaiya** 2022-04-09 00:16 UTC
